#version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5433:5432"  # Fixed port mapping
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lakehouse_net

  redis:
    image: redis:latest
    container_name: redis_broker
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lakehouse_net

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9000:9000"  # API Port
      - "9001:9001"  # Console Port
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 2s
      retries: 5
    networks:
      - lakehouse_net

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
    entrypoint: /bin/bash
    command: -c "airflow db migrate && \
                airflow users create \
                  --username tosoham \
                  --password admin \
                  --firstname Soham \
                  --lastname Das \
                  --role Admin \
                  --email todrsoham@gmail.com"
    networks:
      - lakehouse_net

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully  
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/data
      - ./spark:/opt/airflow/spark_jobs
      - ./notebooks:/opt/airflow/notebooks
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      #- AIRFLOW__CORE__AUTH_MANAGER=airflow.auth.managers.simple.SimpleAuthManager
      - AIRFLOW_CONN_SPARK_DEFAULT=spark://spark-master:7077
      - AIRFLOW_CONN_AWS_DEFAULT=aws://admin:password@?host=http%3A%2F%2Fminio%3A9000
      - AIRFLOW__AUTH_MANAGERS__SIMPLE__ALLOWED_USERS=tosoham:admin,admin:admin
      - AIRFLOW__SECRETS__BACKENDS=airflow.secrets.environment_variables.EnvironmentVariablesBackend,airflow.secrets.metastore.MetastoreBackend
    command: api-server  
    networks:
      - lakehouse_net

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_scheduler
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/data
      - ./spark:/opt/airflow/spark_jobs
      - ./notebooks:/opt/airflow/notebooks
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_AWS_DEFAULT=aws://admin:password@/?endpoint_url=http%3A%2F%2Fminio%3A9000
      - AIRFLOW__SECRETS__BACKENDS=airflow.secrets.environment_variables.EnvironmentVariablesBackend,airflow.secrets.metastore.MetastoreBackend
    command: scheduler
    networks:
      - lakehouse_net

  airflow-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_worker
    restart: always
    depends_on:
      redis:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/data
      - ./spark:/opt/airflow/spark_jobs
      - ./notebooks:/opt/airflow/notebooks
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
      - AIRFLOW_CONN_AWS_DEFAULT=aws://admin:password@/?endpoint_url=http%3A%2F%2Fminio%3A9000
      - AIRFLOW__WEBSERVER__BASE_URL=http://airflow-webserver:8080
      - AIRFLOW__SECRETS__BACKENDS=airflow.secrets.environment_variables.EnvironmentVariablesBackend,airflow.secrets.metastore.MetastoreBackend
    command: celery worker
    networks:
      - lakehouse_net
    mem_limit: 4g
    mem_reservation: 2g

  spark-master:
    image: bitnami/spark:latest
    container_name: spark_master
    ports:
      - "8081:8080"  # Spark Master UI
      - "7077:7077"  # Spark Master Port
    volumes:
      - ./spark:/opt/spark/jobs
      - ./data:/opt/data
      - ./notebooks:/opt/spark/notebooks
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - lakehouse_net

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker_1
    depends_on:
      - spark-master
    ports:
      - "8082:8080"
    volumes:
      - ./spark:/opt/spark/jobs
      - ./data:/opt/data
      - ./notebooks:/opt/spark/notebooks
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - lakehouse_net

  superset:
    image: apache/superset:latest
    container_name: superset_bi
    depends_on:
      - postgres
      - redis
    ports:
      - "8088:8088"
    environment:
      - SUPERSET_SECRET_KEY=a_very_secret_key_for_superset
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://airflow:airflow@postgres/airflow
    command: >
      bash -c "superset db upgrade &&
               superset init &&
               superset fab create-admin --username admin --password admin --firstname Superset --lastname Admin --email admin@superset.com &&
               superset set_database_uri -d 'airflow_db' -u 'postgresql+psycopg2://airflow:airflow@postgres/airflow' &&
               gunicorn --bind 0.0.0.0:8088 'superset.app:create_app()'"
    networks:
      - lakehouse_net

volumes:
  postgres-data:
  minio-data:

networks:
  lakehouse_net:
    driver: bridge